# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 07:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=200, verbose_name='Описание статьи')),
                ('body', redactor.fields.RedactorField(verbose_name='Text')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='media', verbose_name='Превью', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('d', 'part'), ('p', 'Published')], max_length=1, verbose_name='Статус')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотр')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('topped', models.BooleanField(default=False, verbose_name='Топ')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name_plural': 'Статьи',
                'verbose_name': 'Статья',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Категория')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Последняя модификация')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=20, verbose_name='Имя контакта')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Ваш email')),
                ('content', models.CharField(max_length=200, verbose_name='Текст сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя тэга')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='Дата последней модификации')),
            ],
            options={
                'verbose_name_plural': 'Тэги',
                'verbose_name': 'Тэг',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.Tag', verbose_name='Тэг'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
